variable "unique_name_suffix" {
  description = "A suffix to name resources generated by this config (defaults to the empty string).  If left empty, an 8-character random identifier will be generated and used."
  type = string
  default = ""
}

variable "cluster_config_dir" {
  description = "The directory containing the workspace the EKS cluster was provisioned from.  By default this is assumed to be named `cluster` and to exist alongside this config.  Note: see also `cluster_config_cluster_name_output` and `cluster_name`."
  type = string
  default = "../cluster"
}

variable "cluster_config_cluster_name_output" {
  description = "The name of the output from the config that provisioned the cluster, if any, which contains the EKS cluster name (defaults to 'kubeconfig_eks_cluster_name').  Note: see also `cluster_config_dir` and `cluster_name`."
  type = string
  default = "kubeconfig_eks_cluster_name"
}

variable "cluster_name" {
  description = "The name of the cluster to install addons into.  If the cluster was provisioned using a Terraform config, and that config directory and the cluster name output are set correctly (see `cluster_config_dir` and `cluster_config_cluster_name_output`), setting this is not necessary but will not break anything."
  type = string
  default = null
}

variable "cluster_config_aws_region_output" {
  description = "The name of the output from the config that provisioned the cluster, if any, which contains the name of the AWS region the cluster was provisioned in (defaults to 'aws_eks_region').  Note: see also `cluster_config_dir` and `aws_region`.  If not set or discovered, the region of the current account is used."
  type = string
  default = "aws_eks_region"
}

variable "aws_region" {
  description = "The name of the AWS region the target cluster was provisioned in.  If the cluster was provisioned using a Terraform config, and that config directory and the cluster name output are set correctly (see `cluster_config_dir` and `cluster_config_aws_region_output`), setting this is not necessary but will not break anything."
  type = string
  default = null
}

variable "basic_addons" {
  description = "A list of addons that should be installed by default.  Valid values are any EKS addon name string.  If additional resources must be installed to support a desired addon, add them to main.tf as per the example resource in that file."
  type = list(string)
  nullable = false
  default = [ "aws-ebs-csi-driver", "snapshot-controller", "eks-pod-identity-agent", "metrics-server", "cert-manager" ]
}

variable "extra_addons" {
  description = "A list of additional addons that should be installed.  Valid values are any EKS addon name string.  If additional resources must be installed to support a desired addon, add them to main.tf as per the example resource in that file."
  type = list(string)
  default = []
}

variable "skip_addons" {
  description = "(Not implemented) A list of addons that should always be skipped.  Valid values are any EKS addon name string, but listing addons that are not in the `basic_addons` list has no effect.  Note: if an addon is listed both here and in `extra_addons`, it will be installed."
  type = list(string)
  default = []
}